[package]
name = "screencapturekit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
objc = "0.2.7"
objc_id = "0.1.1"
block = "0.1.0"

