[workspace]

members = [
  "screencapturekit-sys",
  "screencapturekit",
  "tauri-plugin-gstreamer",
  "src-tauri",
  "gstreamer-screenshare-plugin",
]

[workspace.package]
edition = "2021"

[profile.dev]
rpath = true
