[package]
name = "doom-capture-sys"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
log = "0.4"
pretty_env_logger = "0.4"
color-backtrace = "0.5.1"
env_logger = "0.9"

[dependencies]
objc = "0.2.7"
block = "0.1.6"

[build-dependencies]
apple-bindgen = { path = "./apple-sys/bindgen"}

