name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  bindgen:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Test
      run: cargo test  --manifest-path=bindgen/Cargo.toml --verbose
    - name: Tool
      run: cargo run --features=bin --manifest-path=bindgen/Cargo.toml --verbose CoreFoundation --sdk macosx

  sys:
    strategy:
      matrix:
        feature: [
          AGL,
          AVFAudio,
          AVFoundation,
          AVKit,
          Accelerate,
          Accessibility,
          Accounts,
          AdServices,
          AdSupport,
          AddressBook,
          AppKit,
          AppTrackingTransparency,
          AppleScriptKit,
          AppleScriptObjC,
          ApplicationServices,
          AudioToolbox,
          AudioUnit,
          AudioVideoBridging,
          AuthenticationServices,
          AutomaticAssessmentConfiguration,
          Automator,
          BackgroundTasks,
          BusinessChat,
          CFNetwork,
          CHIP,
          CalendarStore,
          CallKit,
          Carbon,
          ClassKit,
          CloudKit,
          Cocoa,
          Collaboration,
          ColorSync,
          Contacts,
          ContactsUI,
          CoreAudio,
          CoreAudioKit,
          CoreBluetooth,
          CoreData,
          CoreFoundation,
          CoreGraphics,
          CoreHaptics,
          CoreImage,
          CoreLocation,
          CoreMIDI,
          CoreML,
          CoreMedia,
          CoreMediaIO,
          CoreMotion,
          CoreServices,
          CoreSpotlight,
          CoreTelephony,
          CoreText,
          CoreVideo,
          CoreWLAN,
          CryptoTokenKit,
          DVDPlayback,
          DataDetection,
          DeviceCheck,
          DirectoryService,
          DiscRecording,
          DiscRecordingUI,
          DiskArbitration,
          EventKit,
          ExceptionHandling,
          ExecutionPolicy,
          ExposureNotification,
          ExternalAccessory,
          FWAUserLib,
          FileProvider,
          FileProviderUI,
          FinderSync,
          ForceFeedback,
          Foundation,
          GLKit,
          GLUT,
          GSS,
          GameController,
          GameKit,
          GameplayKit,
          Hypervisor,
          ICADevices,
          IMServicePlugIn,
          IOBluetooth,
          IOBluetoothUI,
          IOKit,
          IOSurface,
          IOUSBHost,
          IdentityLookup,
          ImageCaptureCore,
          ImageIO,
          InputMethodKit,
          InstallerPlugins,
          InstantMessage,
          Intents,
          IntentsUI,
          JavaNativeFoundation,
          JavaRuntimeSupport,
          JavaScriptCore,
          Kerberos,
          KernelManagement,
          LDAP,
          LatentSemanticMapping,
          LinkPresentation,
          LocalAuthentication,
          LocalAuthenticationEmbeddedUI,
          MLCompute,
          MailKit,
          MapKit,
          MediaAccessibility,
          MediaLibrary,
          MediaPlayer,
          MediaToolbox,
          Metal,
          MetalKit,
          # MetalPerformanceShaders,  -- exceed max arg
          # MetalPerformanceShadersGraph,  -- exceed max arg
          MetricKit,
          ModelIO,
          MultipeerConnectivity,
          NaturalLanguage,
          NearbyInteraction,
          NetFS,
          Network,
          NetworkExtension,
          NotificationCenter,
          OSAKit,
          OSLog,
          OpenAL,
          OpenCL,
          OpenDirectory,
          OpenGL,
          PCSC,
          PDFKit,
          PHASE,
          ParavirtualizedGraphics,
          PassKit,
          PencilKit,
          Photos,
          PhotosUI,
          PreferencePanes,
          PushKit,
          Quartz,
          QuartzCore,
          QuickLook,
          QuickLookThumbnailing,
          QuickLookUI,
          ReplayKit,
          SafariServices,
          SceneKit,
          # ScreenCaptureKit,  -- failing on CI env
          ScreenSaver,
          ScreenTime,
          ScriptingBridge,
          Security,
          SecurityFoundation,
          SecurityInterface,
          SensorKit,
          ServiceManagement,
          ShazamKit,
          Social,
          SoundAnalysis,
          Speech,
          SpriteKit,
          StoreKit,
          SwiftUI,
          SyncServices,
          SystemConfiguration,
          SystemExtensions,
          TWAIN,
          Tcl,
          UniformTypeIdentifiers,
          UserNotifications,
          UserNotificationsUI,
          VideoDecodeAcceleration,
          VideoSubscriberAccount,
          VideoToolbox,
          Virtualization,
          Vision,
          # WebKit,  -- exceed max arg
          WidgetKit,
          iTunesLibrary,
          vmnet
        ]
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build  --manifest-path=sys/Cargo.toml --verbose --features ${{ matrix.feature }}
